import Head from "next/head";
import Navbar from "../components/Navbar";
import Banner from "../components/Banner";
import CareerGoal from "../components/CareerGoal";

export default function Home() {
  return (
    <>
      <Head>
        <title>Online Learning</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Banner />
        <CareerGoal />
      </main>
    </>
  );
}
